version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/flowlyhub?sslmode=disable
      - JWT_SECRET=your_super_secret_jwt_key_12345
      - PORT=8080
      - WEATHER_API_KEY=ba12029906bc0e223e15aaca3eff4d34
      - WEATHER_API_BASE_URL=https://api.openweathermap.org/data/2.5 # <-- TAMBAHKAN INI
    depends_on:
      db:
        condition: service_healthy # <-- PENTING: Tunggu sampai db benar-benar sehat
    restart: always # Otomatis restart jika app crash

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flowlyhub
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # <-- PENTING: Healthcheck untuk database
      test: ["CMD-SHELL", "pg_isready -U user -d flowlyhub"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
