// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Absence struct {
	ID           int32              `json:"id"`
	IDKaryawan   int32              `json:"id_karyawan"`
	NamaKaryawan string             `json:"nama_karyawan"`
	Tanggal      pgtype.Date        `json:"tanggal"`
	JamMasuk     pgtype.Time        `json:"jam_masuk"`
	JamJadwal    pgtype.Time        `json:"jam_jadwal"`
	Terlambat    bool               `json:"terlambat"`
	Cuaca        pgtype.Text        `json:"cuaca"`
	Latitude     float64            `json:"latitude"`
	Longitude    float64            `json:"longitude"`
	Hari         string             `json:"hari"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
