// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Absence struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	ClockIn   pgtype.Timestamptz `json:"clock_in"`
	ClockOut  pgtype.Timestamptz `json:"clock_out"`
	Location  pgtype.Text        `json:"location"`
	Weather   pgtype.Text        `json:"weather"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Report struct {
	ID                int32              `json:"id"`
	Tanggal           pgtype.Timestamptz `json:"tanggal"`
	JenisTransaksi    string             `json:"jenis_transaksi"`
	KategoriTransaksi string             `json:"kategori_transaksi"`
	Jumlah            pgtype.Numeric     `json:"jumlah"`
	Keterangan        pgtype.Text        `json:"keterangan"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Stock struct {
	ID             int32              `json:"id"`
	Tanggal        pgtype.Timestamptz `json:"tanggal"`
	NamaMenu       string             `json:"nama_menu"`
	JumlahTerjual  int32              `json:"jumlah_terjual"`
	KategoriMenu   pgtype.Text        `json:"kategori_menu"`
	HargaSatuan    pgtype.Numeric     `json:"harga_satuan"`
	TotalPenjualan pgtype.Numeric     `json:"total_penjualan"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
